# Name of workflow
name: Netlify

# When workflow is triggered
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      branches: [ "main" ]

# Jobs to carry out
jobs:
  build:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Run npm install and build
      - run: npm install
      - run: npm run build --if-present
      # Deploy to Netlify using our dev secrets
      # - name: Deploy to netlify
      #   uses: netlify/actions/cli@master
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}

